#!/bin/bash
# This script updates /etc/hosts to remap localhost and facebook.com

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

cp /etc/hosts /etc/hosts.bak

sed -i '/127\.0\.0\.1\s\+localhost/d' /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts